# 설정 변수들 저장 파일.

px_per_m_x: 23
px_per_m_y: 23
scan_interval: 0.2
filter_window: 5
k_neighbors: 3
map_file: "2GONG.png"

rooms:
  - name: 101호
    x: 7.10
    y: 5.40
  - name: 102호
    x: 7.10
    y: 14.20
  - name: 103호
    x: 18.75
    y: 14.20


beacon_macs:
  - "C3:00:00:44:DC:1A"
  - "C3:00:00:44:DC:1B"
  - "C3:00:00:44:DC:1C"
  - "C3:00:00:44:DC:1D"
  - "C3:00:00:44:DC:1E"
  - "C3:00:00:44:DC:1F"