# 설정 변수들 저장 파일.

px_per_m_x: 35.2
px_per_m_y: 35.2
scan_interval: 0.2
filter_window: 5
k_neighbors: 3
map_file: "2GONG.png"

rooms:
  - name: 101호
    x: 1.39
    y: 5.82
  - name: 102호
    x: 9.7
    y: 9.7
  - name: 103호
    x: 13.2
    y: 9.7


beacon_macs:
  - "C3:00:00:44:DC:1A"
  - "C3:00:00:44:DC:1B"
  - "C3:00:00:44:DC:1C"
  - "C3:00:00:44:DC:1D"
  - "C3:00:00:44:DC:1E"
  - "C3:00:00:44:DC:1F"